name: "Sphinx error reporter (problem matcher)"

description: "Searches for problems in Sphinx output and reports them in PRs and action summaries"

author: "taminomara"

branding:
  icon: "book"
  color: "green"

inputs:
  action:
    description: "The action to take on the problem matcher (add or remove)"
    required: false
    default: add

runs:
  using: "node16"
  main: "dist/index.js"
